config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  
  root "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create!(post_params)
    redirect_to post
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id, :to_name, :letter_color, :stamp_color)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeThankYou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- レスポンシブ対応 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">自分の名前</th>
      <th scope="col">相手の名前</th>
      <th scope="col">相手の名前</th>


      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each.with_index(1) do |post, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= post.user_id %></td>
        <td>
          <%= link_to "詳細", post %>
          <%= link_to "削除", post, method: :delete, data: { confirm: "削除しますか?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<P>自由に感謝を書いてください</P>
<P>※下記項目は全て必須項目です</P>
<P>※改行は反映されません</P>
<%= form_with model: @post, local: true do |form| %>
  <div>
    <%= form.label :user_id, "自分の名前" %>
    <%= form.text_field :user_id  %>
  </div>
  <div>
    <%= form.label :to_name, "相手の名前" %>
    <%= form.text_field :to_name %>
  </div>
    <div>
    <%= form.label :body, "内容" %>
    <%= form.text_field :body %>
  </div>
    <div>
    <%= form.label :letter_color, "手紙の色" %>
    <%= form.text_field :letter_color %>
  </div>
    <div>
    <%= form.label :stamp_color, "切手の色" %>
    <%= form.text_field :stamp_color %>
  </div>
  <div>
    <%= form.submit "送信" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>自分の名前 <%= @post.user_id %></p>
<p>相手の名前 <%= @post.to_name %></p>
<p>センキュー内容 <%= @post.body %></p>
<p>手紙の色 <%= @post.letter_color %></p>
<p>切手の色 <%= @post.stamp_color %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>
<button type="button" class="btn btn-primary">Primary</button>

<!-- フィルタリングを行うための検索窓 -->
<input class="form-control" id="myInput" type="text" placeholder="Search Curriculum..">

<!-- テーブル -->
<table class="table table-striped">
  <thead class="bg-danger text-white">
    <tr>
      <th>言語</th>
      <th>説明</th>
    </tr>
  </thead>
  <tbody id="myTable">
    <tr>
      <td>HTML/CSS</td>
      <td>Webサイトの画面を作るための言語</td>
    </tr>
    <tr>
      <td>Ruby</td>
      <td>Webサイトの裏側の処理をする言語</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>人工知能を開発するための言語</td>
    </tr>
  </tbody>
</table>

<!-- テーブルのフィルター機能を追加 -->
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h2>投稿内容</h2>
<% @user.posts.each do |post| %>
  <a href="/posts/<%= post.id %>"><%= post.body %></a>
  <hr>
<% end %>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", posts_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>